### ISSUE TITLE
How to use with Berlin52 instance

### ISSUE THREAD

**Issue by wellingtoncosta** [polatbilek/Tabu-search-on-Travelling-Salesman-Problem#1]
Hi,

Firstly I would like to thank you so much for the great implementation. So, I would like to use your implementation using [berlin52](http://elib.zib.de/pub/mp-testdata/tsp/tsplib/tsp/berlin52.tsp) instance but the expected data format is based in a kind of triplet. Do you have an variant implementation to support berlin52 format?

**Comment by polatbilek** [comment]
The dataset already specfies the weight type as 
`EDGE_WEIGHT_TYPE: EUC_2D`

So, all you need to do calculate distances among all data points, and assume that all nodes are connected to other ones with a weight w.r.t. their euclidean distance. So it will be 52x52 matrix, where each element represents an edge, the indexes are the nodes that the edge is connected to. In this way you can feed the data into code, also your dataset suggests to use it that way.

So a code snippet something like below should adapt the data to the code.
```
dataset = [52] #I assume that you already read the data from .txt to dataset variable
data_points = numpy.zeros((52,52))
for i in range(52):
    for j in range(52):
        data_points[i][j] = eclidean_distance(dataset[i], dataset[j]) #this function is already implemented in code
```
